hmcts/ts-translation-service

charts/ts-translation-service/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/WLTS-14
Add S2S secret to preview chart
```
[ ] Yes
[X] No
```
=> WLTS-14 - read S2S secret from preview vault

build.gradle, src/functionalTest/resources/DummyTest.xml, src/main/resources/application.yaml
[WLTS-2](https://tools.hmcts.net/jira/browse/WLTS-2) _"Welsh Language Support for Professional Users "_ (epic)
Adjusments to smoke test configuration.
```
[ ] Yes
[x] No
```
=> Smoke test patch

src/functionalTest/resources/features/F-002 - Put Dictionary/S-002.8.td.json
https://tools.hmcts.net/jira/browse/WLTS-17
Small change for Scenario S-002.8
```
[ ] Yes
[X ] No
```
=> WLTS-17 FT Patch

build.gradle, src/functionalTest/resources/features/F-003 - Request Translations/F-003_Get_Dictionary.td.json, src/functionalTest/resources/features/F-003 - Request Translations/F-003_Put_Dictionary.td.json, src/functionalTest/resources/features/F-003 - Request Translations/S-003.1.td.json, src/functionalTest/resources/features/F-003 - Request Translations/S-003.2.td.json, src/functionalTest/resources/features/F-003 - Request Translations/S-003.3.td.json, src/functionalTest/resources/features/F-003 - Request Translations/S-003.5.td.json, src/functionalTest/resources/features/F-003 - Request Translations/S-003.6.td.json, src/functionalTest/resources/features/F-003 - Request Translations/S-003.7.td.json, src/integrationTest/java/uk/gov/hmcts/reform/translate/BaseTest.java, src/integrationTest/java/uk/gov/hmcts/reform/translate/controllers/DictionaryControllerIT.java, src/integrationTest/java/uk/gov/hmcts/reform/translate/controllers/TestingSupportControllerIT.java, src/integrationTest/java/uk/gov/hmcts/reform/translate/repository/DefaultDictionaryRepositoryIT.java, src/main/java/uk/gov/hmcts/reform/translate/Application.java, src/main/java/uk/gov/hmcts/reform/translate/errorhandling/ApiException.java, src/main/java/uk/gov/hmcts/reform/translate/errorhandling/EnglishPhraseUniqueConstraintException.java, src/main/java/uk/gov/hmcts/reform/translate/repository/DefaultDictionaryRepository.java, src/main/java/uk/gov/hmcts/reform/translate/repository/DictionaryRepository.java, src/main/java/uk/gov/hmcts/reform/translate/repository/JpaDictionaryRepository.java, src/main/java/uk/gov/hmcts/reform/translate/service/DictionaryService.java, src/test/java/uk/gov/hmcts/reform/translate/errorhandling/RestExceptionHandlerTest.java, src/test/java/uk/gov/hmcts/reform/translate/repository/DefaultDictionaryRepositoryTest.java, src/test/java/uk/gov/hmcts/reform/translate/service/DictionaryServiceTest.java, src/test/java/uk/gov/hmcts/reform/translate/service/DictionaryServiceWithRetryEnabledTest.java
[WLTS-43](https://tools.hmcts.net/jira/browse/WLTS-43) _"Failing pipelines due to concurrency/conflict issues when generating test data."_
Retry Get and Put services on conflict
> ~~Note: this PR is based of: #60~~
```
[ ] Yes
[x] No
```
=> WLTS-43 Retry Get and Put services on conflict

config/owasp/suppressions.xml
WLTS-44 (https://tools.hmcts.net/jira/browse/WLTS-44)
Updated suppressions file to temporarily suppress CVE-2022-31197.
```
[ ] Yes
[x] No
```
=> WLTS-44: Temporarily suppress CVE-2022-31197

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/WLTS-48
https://tools.hmcts.net/jira/browse/WLTS-47
https://tools.hmcts.net/jira/browse/WLTS-46
Temporary suppression of CVEs:
CVE-2022-38751 
CVE-2022-38750 
CVE-2022-38749
CVE-2022-38752
CVE-2022-42003
CVE-2022-42004
```
[ ] Yes
[X] No
```
=> WLTS-48, WLTS-47 and WLTS-46 Temporarily suppressing CVEs

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/WLTS-57
WLTS-57-CVE-2022-41854-Suppression
```
[ ] Yes
[X] No
```
=> WLTS-57-CVE-2022-41854-Suppression

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/WLTS-37
https://tools.hmcts.net/jira/browse/WLTS-38
https://tools.hmcts.net/jira/browse/WLTS-39
https://tools.hmcts.net/jira/browse/WLTS-44
https://tools.hmcts.net/jira/browse/WLTS-45
https://tools.hmcts.net/jira/browse/WLTS-46
https://tools.hmcts.net/jira/browse/WLTS-47
https://tools.hmcts.net/jira/browse/WLTS-48
https://tools.hmcts.net/jira/browse/WLTS-52
https://tools.hmcts.net/jira/browse/WLTS-53
https://tools.hmcts.net/jira/browse/WLTS-57
Fix 15 CVEs (CVE-2020-5408 , CVE-2022-34305 , CVE-2022-33915 , CVE-2022-31197 , CVE-2022-25857 , CVE-2022-38751 , CVE-2022-38750 , CVE-2022-38749 , CVE-2022-38752 , CVE-2022-42003 , CVE-2022-42004 , CVE-2022-31690 , CVE-2022-31692 , CVE-2022-42252 , CVE-2022-41854).
**Does this PR introduce a breaking change?** …
=> WLTS: Fix CVEs for which we have a solution in CCD.

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/WLTS-58
Updated uk.gov.hmcts.java version to 0.12.33.
Removed old suppressions.
Verified that dependencyCheckAggregate passes locally and pull request pipeline passes.
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
=> WLTS-58: Check CVEs showing on ts-translation-service

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/WLTS-59
CVE-2021-37533 Suppression
```
[ ] Yes
[ x] No
```
=> WLTS-59 CVE-2021-37533 Suppression

Jenkinsfile_CNP, build.gradle
https://tools.hmcts.net/jira/browse/CCD-4050
Fix Jenkins pipeline warnings regarding Groovy after() statements.
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
=> CCD-4050: Fix Jenkins pipeline warnings

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/WLTS-62
Update suppressions.xml
```
[ ] Yes
[X] No
```
=> WLTS-62 : Update suppressions.xml

build.gradle
https://tools.hmcts.net/jira/browse/WLTS-63
Bump rse-gradle plugin to add dependency-check v8.0.2
```
[ ] Yes
[X] No
```
=> WLTS-63 Bump rse-gradle plugin to add dependency-check v8.0.2

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/WLTS-65
Fix CVE-2022-45143.
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
=> WLTS-65: Fix CVE-2022-45143

build.gradle, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/CCD-4408
```
[ ] Yes
[ ] No
```
=> update befta-fw version to 8.7.11

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/WLTS-71
Fix for : CVE-2023-20859, CVE-2023-20863 and CVE-2023-20863
```
[ ] Yes
[X] No
```
=> WLTS-71 : fix for various CVEs

.github/renovate.json, charts/ts-translation-service/Chart.yaml
NA
Fix for nightly build failure deprecated config in renovate.json
```
[ ] Yes
[X] No
```
=> Fix nightly pipeline - deprecated config in renovate.json

acb.tpl.yaml, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/HMAN-602
Add retries to all acb.tpl.yaml entries
```
[ ] Yes
[x ] No
```
=> HMAN-602 : Add retries to all acb.tpl.yaml entries

acb.tpl.yaml
https://tools.hmcts.net/jira/browse/HMAN-602
=> Fix retries issues

.gitignore, Dockerfile, build.gradle, charts/ts-translation-service/Chart.yaml, charts/ts-translation-service/values.preview.template.yaml, charts/ts-translation-service/values.yaml, infrastructure/app-insights.tf, lib/applicationinsights.json, src/main/resources/application.yaml
Attempt to fix ApplicationInsights
https://tools.hmcts.net/jira/browse/CCD-5150
```
[ ] Yes
[ x] No
```
=> Attempt to fix ApplicationInsights

infrastructure/app-insights.tf
https://tools.hmcts.net/jira/browse/CCD-5150
Remove unneeded secret entry breaking pipeline
```
[ ] Yes
[ x] No
```
=> Remove unneeded secret entry

infrastructure/main.tf
https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1382&projectKey=CCD&view=detail&selectedIssue=CCD-5138
Adding conditional count to V11 module in order to decommission all migrated PostgreSQL databases bar prod which has yet to be migrated.
=> Adding conditional count, delete all envs bar prod

infrastructure/main.tf
https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1382&projectKey=CCD&view=detail&selectedIssue=CCD-5138
Delete all migrated V11s (demo, ithc, perftest, aat) bar prod 
```
[ ] Yes
[x] No
```
=> Adding prevent deletion flag to false

charts/ts-translation-service/Chart.yaml, infrastructure/main.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1382&projectKey=CCD&view=detail&selectedIssue=CCD-5138
Update v15 db config after migration on all environments including Prod.
```
[ ] Yes
[x] No
```
=> Update v15 db config after migration on all environments including Prod

build.gradle, config/owasp/suppressions.xml
CVE-2023-33202 : Bump spring-security-rsa
https://tools.hmcts.net/jira/browse/CCD-5076
```
[ ] Yes
[ x] No
```
=> CVE-2023-33202 : Bump spring-security-rsa

charts/ts-translation-service/Chart.yaml
Bumped chart-Java version to latest
https://tools.hmcts.net/jira/browse/CCD-5339
Bumped chart-java to latest
```
[ ] Yes
[X] No
```
=> CCD-5339 - Update Chart.yaml

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-5201
Bumped spring security version to resolve CVE-2023-34042
```
[ ] Yes
[x] No
```
=> CCD-5201 Bumped spring security version to resolve CVE-2023-34042

config/owasp/suppressions.xml
**CCD-5652_CVE_fix**
-
CCD-5652
cve fix
```
[ ] Yes
[ ] No
```
=> CCD-5652_CVE_fix

infrastructure/main.tf, infrastructure/state.tf
NA
bump tf and fix for master
```
[ ] Yes
[X] No
```
=> Fix master tf

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-5193
removed suppression as not needed
```
[ ] Yes
[X] No
```
=> CCD-5193: Fix: CVE-2022-45047

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-5193
bumped to fix CVE
```
[ ] Yes
[X] No
```
=> CCD-5193 : Fix : CVE-2022-45047

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-5925
CCD-5925-Tidy-Suppressions
```
[ ] Yes
[X] No
```
=> CCD-5925-Tidy-Suppressions

infrastructure/state.tf
https://tools.hmcts.net/jira/browse/CME-317
Standardise version
```
[ ] Yes
[ x] No
```
=> CME-317: Update azurerm 

.github/workflows/dependency-check.yml, .github/workflows/swagger.yml
https://tools.hmcts.net/jira/browse/CCD-6098
```
[ ] Yes
[ ] No
```
=> CCD-6098 Update cache to v4

charts/ts-translation-service/Chart.yaml
https://tools.hmcts.net/jira/browse/CCD-6193
```
[ ] Yes
[ ] No
```
=> CCD-6193 update base chart version

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CFTS-6917
https://tools.hmcts.net/jira/browse/CFTS-6915
https://tools.hmcts.net/jira/browse/CFTS-6916
```
[ ] Yes
[X] No
```
=> CFTS-6917: Suppress CVE

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-6362
Suppress CVE-2024-52316
```
[ ] Yes
[X] No
```
=> CCD-6362 :: Suppress CVE-2024-52316

infrastructure/aat.tfvars, infrastructure/main.tf, infrastructure/variables.tf
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
=> Add CCD for Preview

build.gradle, settings.gradle
https://tools.hmcts.net/jira/browse/CME-679
Replaced JitPack with Azure Artifacts
```
[ ] Yes
[X] No
```
=> CME-679 Replace JitPack with Azure Artifacts

.github/workflows/swagger.yml, src/functionalTest/java/uk/gov/hmcts/reform/translate/TranslationServiceTestAutomationAdapter.java, src/functionalTest/resources/features/F-125 - Swagger Pages and API Specs/F-125.feature, src/functionalTest/resources/features/F-125 - Swagger Pages and API Specs/F-125_Test_Swagger_JSON_Base_Data.td.json, src/functionalTest/resources/features/F-125 - Swagger Pages and API Specs/F-125_Test_Swagger_UI_Base_Data.td.json, src/functionalTest/resources/features/F-125 - Swagger Pages and API Specs/S-125.1.td.json, src/functionalTest/resources/features/F-125 - Swagger Pages and API Specs/S-125.2.td.json, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/CCD-6268
CCD-6268 :: added Ft's for swagger testing
```
[ ] Yes
[X] No
```
=> CCD-6268 :: added Ft's for swagger testing
